version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: "apache-cicd"  # Must match container name in taskdef.json
          ContainerPort: 5000
