version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:471101288063:task-definition/mytask:24"
        LoadBalancerInfo:
          ContainerName: "apache-cicd"
          ContainerPort: 5000
