version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471101288063.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - IMAGE_URI="471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest"
      - docker build -t ecswithpipeline .
      - docker tag ecswithpipeline:latest $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      - echo '[{"name":"apache-cicd","imageUri":"'"$IMAGE_URI"'"}]' > $CODEBUILD_SRC_DIR/imagedefinitions.json
      - echo "Verifying imagedefinitions.json:"
      - ls -la $CODEBUILD_SRC_DIR/
      - cat $CODEBUILD_SRC_DIR/imagedefinitions.json
      - |
       cat <<EOF > taskdef.json
       {
        "family": "mytask",
        "containerDefinitions": [
          {
            "name": "apache-cicd",
            "image": "<IMAGE_URI>",  # MUST match placeholder exactly
            "portMappings": [{"containerPort": 5000}]
          }
        ]
       }
       EOF
      - echo "imagedefinitions.json content:"
      - cat imagedefinitions.json
      - echo "taskdef.json content:"
      - cat taskdef.json
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
  base-directory: $CODEBUILD_SRC_DIR
