version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471101288063.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - IMAGE_URI=471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest
      - docker build -t ecswithpipeline:latest .
      - docker tag ecswithpipeline:latest $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      - printf '[{"name":"apache-container-5000","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Writing taskdef.json...
      - |
        cat <<EOF > taskdef.json
        {
          "family": "mytask",
          "executionRoleArn": "arn:aws:iam::471101288063:role/ecsTaskExecutionRole",
          "networkMode": "awsvpc",
          "containerDefinitions": [
            {
              "name": "apache-container-5000",
              "image": "471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest",
              "portMappings": [
                {
                  "name": "apache-container-5000",
                  "containerPort": 5000,
                  "hostPort": 5000,
                  "protocol": "tcp",
                  "appProtocol": "http"
                }
              ],
              "essential": true,
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/mytask",
                  "awslogs-region": "us-east-1",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "3072"
        }
        EOF
artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
    - taskdef.json
