version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471101288063.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - IMAGE_URI="471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest"
      - docker build -t ecswithpipeline .
      - docker tag ecswithpipeline:latest $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      - echo '[{"name":"apache-cicd","imageUri":"'"$IMAGE_URI"'"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - |
        cat <<EOF > taskdef.json
        {
          "family": "mytask",
          "executionRoleArn": "arn:aws:iam::471101288063:role/ecsTaskExecutionRole",
          "networkMode": "awsvpc",
          "containerDefinitions": [
            {
              "name": "apache-cicd",
              "image": "$IMAGE_URI",
              "portMappings": [
                {
                  "containerPort": 5000,
                  "hostPort": 5000,
                  "protocol": "tcp"
                }
              ],
              "essential": true
            }
          ],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "3072"
        }
        EOF
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
