version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471101288063.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - IMAGE_URI="471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest"
      - docker build -t ecswithpipeline .
      - docker tag ecswithpipeline:latest $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      # Fix: Generate PROPER imagedefinitions.json with correct structure
      - echo '[{"name":"apache-cicd","imageUri":"'"$IMAGE_URI"'"}]' > imagedefinitions.json
      # Verify the file content
      - cat imagedefinitions.json
      # Generate taskdef.json with EXACTLY matching container name
      - |
        cat <<EOF > taskdef.json
        {
          "family": "mytask",
          "containerDefinitions": [
            {
              "name": "apache-cicd",  # MUST match imagedefinitions.json
              "image": "$IMAGE_URI",
              "portMappings": [{"containerPort": 5000}],
              "essential": true
            }
          ],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "3072"
        }
        EOF
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
