version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471101288063.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t ecswithpipeline:latest .
      - docker tag ecswithpipeline:latest 471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest
  post_build:
    commands:
      - docker push 471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest
      - printf '[{"name":"apache-cicd","imageUri":"%s"}]' 471101288063.dkr.ecr.us-east-1.amazonaws.com/ecswithpipeline:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
